// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ExportRequestFormat.
const (
	Csv  ExportRequestFormat = "csv"
	Json ExportRequestFormat = "json"
)

// Defines values for GetTableRowsParamsSortOrder.
const (
	ASC  GetTableRowsParamsSortOrder = "ASC"
	DESC GetTableRowsParamsSortOrder = "DESC"
)

// Activity defines model for Activity.
type Activity struct {
	Application   string `json:"application"`
	ClientAddr    string `json:"client_addr"`
	Database      string `json:"database"`
	Duration      string `json:"duration"`
	Pid           int    `json:"pid"`
	Query         string `json:"query"`
	State         string `json:"state"`
	User          string `json:"user"`
	WaitEvent     string `json:"wait_event"`
	WaitEventType string `json:"wait_event_type"`
}

// AiGenerateRequest defines model for AiGenerateRequest.
type AiGenerateRequest struct {
	Database string       `json:"database"`
	Messages *[]AiMessage `json:"messages,omitempty"`
	Prompt   string       `json:"prompt"`
}

// AiGenerateResponse defines model for AiGenerateResponse.
type AiGenerateResponse struct {
	Explanation string `json:"explanation"`
	Sql         string `json:"sql"`
}

// AiMessage defines model for AiMessage.
type AiMessage struct {
	Content string `json:"content"`
	Role    string `json:"role"`
}

// AppInfo defines model for AppInfo.
type AppInfo struct {
	Version *string `json:"version,omitempty"`
}

// CancelRequest defines model for CancelRequest.
type CancelRequest struct {
	TabId string `json:"tab_id"`
}

// CellValue defines model for CellValue.
type CellValue = *string

// Column defines model for Column.
type Column struct {
	Comment      *string `json:"comment,omitempty"`
	DefaultValue *string `json:"default_value"`
	IsPrimaryKey bool    `json:"is_primary_key"`
	Name         string  `json:"name"`
	Nullable     bool    `json:"nullable"`
	Position     int     `json:"position"`
	Type         string  `json:"type"`
}

// ConnectRequest defines model for ConnectRequest.
type ConnectRequest struct {
	Url string `json:"url"`
}

// ConnectionInfo defines model for ConnectionInfo.
type ConnectionInfo struct {
	Connected *bool  `json:"connected,omitempty"`
	Database  string `json:"database"`
	Host      string `json:"host"`
	Port      int    `json:"port"`
	User      string `json:"user"`
	Version   string `json:"version"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExportRequest defines model for ExportRequest.
type ExportRequest struct {
	Format ExportRequestFormat `json:"format"`
	Query  string              `json:"query"`
}

// ExportRequestFormat defines model for ExportRequest.Format.
type ExportRequestFormat string

// FunctionDefinition defines model for FunctionDefinition.
type FunctionDefinition struct {
	Arguments  string `json:"arguments"`
	Definition string `json:"definition"`
	Kind       string `json:"kind"`
	Language   string `json:"language"`
	Name       string `json:"name"`
	ReturnType string `json:"return_type"`
	Schema     string `json:"schema"`
	Volatility string `json:"volatility"`
}

// HistoryEntry defines model for HistoryEntry.
type HistoryEntry struct {
	Database   string `json:"database"`
	DurationMs int64  `json:"duration_ms"`
	Error      string `json:"error"`
	ExecutedAt string `json:"executed_at"`
	Id         int    `json:"id"`
	RowCount   int    `json:"row_count"`
	Sql        string `json:"sql"`
}

// HistoryResponse defines model for HistoryResponse.
type HistoryResponse struct {
	Entries []HistoryEntry `json:"entries"`
	Total   int            `json:"total"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	Query string `json:"query"`
	TabId string `json:"tab_id"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	ColumnTypes []string      `json:"column_types"`
	Columns     []string      `json:"columns"`
	DurationMs  int64         `json:"duration_ms"`
	Error       *string       `json:"error,omitempty"`
	RowCount    int           `json:"row_count"`
	Rows        [][]CellValue `json:"rows"`
}

// SavedQuery defines model for SavedQuery.
type SavedQuery struct {
	CreatedAt   string `json:"created_at"`
	Database    string `json:"database"`
	Description string `json:"description"`
	Id          string `json:"id"`
	Shared      bool   `json:"shared"`
	Sql         string `json:"sql"`
	Tags        string `json:"tags"`
	Title       string `json:"title"`
	UpdatedAt   string `json:"updated_at"`
}

// SavedQueryInput defines model for SavedQueryInput.
type SavedQueryInput struct {
	Database    *string `json:"database,omitempty"`
	Description *string `json:"description,omitempty"`
	Sql         string  `json:"sql"`
	Tags        *string `json:"tags,omitempty"`
	Title       string  `json:"title"`
}

// SchemaGroup defines model for SchemaGroup.
type SchemaGroup struct {
	Functions         []SchemaObject `json:"functions"`
	MaterializedViews []SchemaObject `json:"materialized_views"`
	Sequences         []SchemaObject `json:"sequences"`
	Tables            []SchemaObject `json:"tables"`
	Types             []SchemaObject `json:"types"`
	Views             []SchemaObject `json:"views"`
}

// SchemaObject defines model for SchemaObject.
type SchemaObject struct {
	Comment *string `json:"comment,omitempty"`
	Name    string  `json:"name"`
	Schema  string  `json:"schema"`
	Type    string  `json:"type"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Success *bool `json:"success,omitempty"`
}

// SwitchDBRequest defines model for SwitchDBRequest.
type SwitchDBRequest struct {
	Database string `json:"database"`
}

// TableConstraint defines model for TableConstraint.
type TableConstraint struct {
	Columns    *[]string `json:"columns,omitempty"`
	Definition string    `json:"definition"`
	Name       string    `json:"name"`
	Type       string    `json:"type"`
}

// TableIndex defines model for TableIndex.
type TableIndex struct {
	Columns    *[]string `json:"columns,omitempty"`
	Definition string    `json:"definition"`
	IsPrimary  bool      `json:"is_primary"`
	IsUnique   bool      `json:"is_unique"`
	Name       string    `json:"name"`
}

// TableInfo defines model for TableInfo.
type TableInfo struct {
	IndexSize   string `json:"index_size"`
	RowEstimate int64  `json:"row_estimate"`
	TableSize   string `json:"table_size"`
	TotalSize   string `json:"total_size"`
}

// TableRowsResult defines model for TableRowsResult.
type TableRowsResult struct {
	ColumnTypes []string      `json:"column_types"`
	Columns     []string      `json:"columns"`
	Page        int           `json:"page"`
	PageSize    int           `json:"page_size"`
	Rows        [][]CellValue `json:"rows"`
	TotalCount  int           `json:"total_count"`
}

// ListHistoryParams defines parameters for ListHistory.
type ListHistoryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListSavedQueriesParams defines parameters for ListSavedQueries.
type ListSavedQueriesParams struct {
	Database *string `form:"database,omitempty" json:"database,omitempty"`
}

// UpdateSettingsJSONBody defines parameters for UpdateSettings.
type UpdateSettingsJSONBody map[string]string

// GetTableRowsParams defines parameters for GetTableRows.
type GetTableRowsParams struct {
	Limit      *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                         `form:"offset,omitempty" json:"offset,omitempty"`
	SortColumn *string                      `form:"sort_column,omitempty" json:"sort_column,omitempty"`
	SortOrder  *GetTableRowsParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`
}

// GetTableRowsParamsSortOrder defines parameters for GetTableRows.
type GetTableRowsParamsSortOrder string

// AiGenerateJSONRequestBody defines body for AiGenerate for application/json ContentType.
type AiGenerateJSONRequestBody = AiGenerateRequest

// AnalyzeQueryJSONRequestBody defines body for AnalyzeQuery for application/json ContentType.
type AnalyzeQueryJSONRequestBody = QueryRequest

// ConnectJSONRequestBody defines body for Connect for application/json ContentType.
type ConnectJSONRequestBody = ConnectRequest

// ExplainQueryJSONRequestBody defines body for ExplainQuery for application/json ContentType.
type ExplainQueryJSONRequestBody = QueryRequest

// ExportQueryJSONRequestBody defines body for ExportQuery for application/json ContentType.
type ExportQueryJSONRequestBody = ExportRequest

// RunQueryJSONRequestBody defines body for RunQuery for application/json ContentType.
type RunQueryJSONRequestBody = QueryRequest

// CancelQueryJSONRequestBody defines body for CancelQuery for application/json ContentType.
type CancelQueryJSONRequestBody = CancelRequest

// CreateSavedQueryJSONRequestBody defines body for CreateSavedQuery for application/json ContentType.
type CreateSavedQueryJSONRequestBody = SavedQueryInput

// UpdateSavedQueryJSONRequestBody defines body for UpdateSavedQuery for application/json ContentType.
type UpdateSavedQueryJSONRequestBody = SavedQueryInput

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody UpdateSettingsJSONBody

// SwitchDatabaseJSONRequestBody defines body for SwitchDatabase for application/json ContentType.
type SwitchDatabaseJSONRequestBody = SwitchDBRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Running queries from pg_stat_activity
	// (GET /api/activity)
	GetActivity(c *gin.Context)
	// Generate SQL from natural language
	// (POST /api/ai/generate)
	AiGenerate(c *gin.Context)
	// EXPLAIN ANALYZE a SQL query
	// (POST /api/analyze)
	AnalyzeQuery(c *gin.Context)
	// Connect to a PostgreSQL database
	// (POST /api/connect)
	Connect(c *gin.Context)
	// Get current connection info
	// (GET /api/connection)
	GetConnectionInfo(c *gin.Context)
	// List all databases on the server
	// (GET /api/databases)
	ListDatabases(c *gin.Context)
	// Disconnect from the database
	// (POST /api/disconnect)
	Disconnect(c *gin.Context)
	// EXPLAIN a SQL query
	// (POST /api/explain)
	ExplainQuery(c *gin.Context)
	// Export query results as CSV or JSON
	// (POST /api/export)
	ExportQuery(c *gin.Context)
	// Get function or procedure source code
	// (GET /api/functions/{function})
	GetFunctionDefinition(c *gin.Context, function string)
	// Clear all query history
	// (DELETE /api/history)
	ClearHistory(c *gin.Context)
	// List query history
	// (GET /api/history)
	ListHistory(c *gin.Context, params ListHistoryParams)
	// Get app version and feature flags
	// (GET /api/info)
	GetAppInfo(c *gin.Context)
	// All objects grouped by schema and type
	// (GET /api/objects)
	ListObjects(c *gin.Context)
	// Execute SQL query
	// (POST /api/query)
	RunQuery(c *gin.Context)
	// Cancel a running query
	// (POST /api/query/cancel)
	CancelQuery(c *gin.Context)
	// List saved queries
	// (GET /api/saved-queries)
	ListSavedQueries(c *gin.Context, params ListSavedQueriesParams)
	// Create a saved query
	// (POST /api/saved-queries)
	CreateSavedQuery(c *gin.Context)
	// Delete a saved query
	// (DELETE /api/saved-queries/{id})
	DeleteSavedQuery(c *gin.Context, id string)
	// Get a saved query by ID
	// (GET /api/saved-queries/{id})
	GetSavedQuery(c *gin.Context, id string)
	// Update a saved query
	// (PUT /api/saved-queries/{id})
	UpdateSavedQuery(c *gin.Context, id string)
	// List database schemas
	// (GET /api/schemas)
	ListSchemas(c *gin.Context)
	// PostgreSQL server settings
	// (GET /api/server_settings)
	GetServerSettings(c *gin.Context)
	// Get all settings
	// (GET /api/settings)
	GetSettings(c *gin.Context)
	// Update settings
	// (PUT /api/settings)
	UpdateSettings(c *gin.Context)
	// Switch to a different database
	// (POST /api/switchdb)
	SwitchDatabase(c *gin.Context)
	// Get table column definitions
	// (GET /api/tables/{table})
	GetTableColumns(c *gin.Context, table string)
	// Table constraints
	// (GET /api/tables/{table}/constraints)
	GetTableConstraints(c *gin.Context, table string)
	// Table indexes
	// (GET /api/tables/{table}/indexes)
	GetTableIndexes(c *gin.Context, table string)
	// Table size and row estimates
	// (GET /api/tables/{table}/info)
	GetTableInfo(c *gin.Context, table string)
	// Paginated table data
	// (GET /api/tables/{table}/rows)
	GetTableRows(c *gin.Context, table string, params GetTableRowsParams)
	// All tables size and row stats
	// (GET /api/tables_stats)
	GetTablesStats(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetActivity operation middleware
func (siw *ServerInterfaceWrapper) GetActivity(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActivity(c)
}

// AiGenerate operation middleware
func (siw *ServerInterfaceWrapper) AiGenerate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AiGenerate(c)
}

// AnalyzeQuery operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AnalyzeQuery(c)
}

// Connect operation middleware
func (siw *ServerInterfaceWrapper) Connect(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Connect(c)
}

// GetConnectionInfo operation middleware
func (siw *ServerInterfaceWrapper) GetConnectionInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConnectionInfo(c)
}

// ListDatabases operation middleware
func (siw *ServerInterfaceWrapper) ListDatabases(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDatabases(c)
}

// Disconnect operation middleware
func (siw *ServerInterfaceWrapper) Disconnect(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Disconnect(c)
}

// ExplainQuery operation middleware
func (siw *ServerInterfaceWrapper) ExplainQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExplainQuery(c)
}

// ExportQuery operation middleware
func (siw *ServerInterfaceWrapper) ExportQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportQuery(c)
}

// GetFunctionDefinition operation middleware
func (siw *ServerInterfaceWrapper) GetFunctionDefinition(c *gin.Context) {

	var err error

	// ------------- Path parameter "function" -------------
	var function string

	err = runtime.BindStyledParameterWithOptions("simple", "function", c.Param("function"), &function, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter function: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFunctionDefinition(c, function)
}

// ClearHistory operation middleware
func (siw *ServerInterfaceWrapper) ClearHistory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ClearHistory(c)
}

// ListHistory operation middleware
func (siw *ServerInterfaceWrapper) ListHistory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListHistory(c, params)
}

// GetAppInfo operation middleware
func (siw *ServerInterfaceWrapper) GetAppInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAppInfo(c)
}

// ListObjects operation middleware
func (siw *ServerInterfaceWrapper) ListObjects(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListObjects(c)
}

// RunQuery operation middleware
func (siw *ServerInterfaceWrapper) RunQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RunQuery(c)
}

// CancelQuery operation middleware
func (siw *ServerInterfaceWrapper) CancelQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelQuery(c)
}

// ListSavedQueries operation middleware
func (siw *ServerInterfaceWrapper) ListSavedQueries(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSavedQueriesParams

	// ------------- Optional query parameter "database" -------------

	err = runtime.BindQueryParameter("form", true, false, "database", c.Request.URL.Query(), &params.Database)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter database: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSavedQueries(c, params)
}

// CreateSavedQuery operation middleware
func (siw *ServerInterfaceWrapper) CreateSavedQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSavedQuery(c)
}

// DeleteSavedQuery operation middleware
func (siw *ServerInterfaceWrapper) DeleteSavedQuery(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSavedQuery(c, id)
}

// GetSavedQuery operation middleware
func (siw *ServerInterfaceWrapper) GetSavedQuery(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSavedQuery(c, id)
}

// UpdateSavedQuery operation middleware
func (siw *ServerInterfaceWrapper) UpdateSavedQuery(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateSavedQuery(c, id)
}

// ListSchemas operation middleware
func (siw *ServerInterfaceWrapper) ListSchemas(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSchemas(c)
}

// GetServerSettings operation middleware
func (siw *ServerInterfaceWrapper) GetServerSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServerSettings(c)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSettings(c)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateSettings(c)
}

// SwitchDatabase operation middleware
func (siw *ServerInterfaceWrapper) SwitchDatabase(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SwitchDatabase(c)
}

// GetTableColumns operation middleware
func (siw *ServerInterfaceWrapper) GetTableColumns(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableColumns(c, table)
}

// GetTableConstraints operation middleware
func (siw *ServerInterfaceWrapper) GetTableConstraints(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableConstraints(c, table)
}

// GetTableIndexes operation middleware
func (siw *ServerInterfaceWrapper) GetTableIndexes(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableIndexes(c, table)
}

// GetTableInfo operation middleware
func (siw *ServerInterfaceWrapper) GetTableInfo(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableInfo(c, table)
}

// GetTableRows operation middleware
func (siw *ServerInterfaceWrapper) GetTableRows(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTableRowsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort_column" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_column", c.Request.URL.Query(), &params.SortColumn)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_column: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort_order" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_order", c.Request.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_order: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableRows(c, table, params)
}

// GetTablesStats operation middleware
func (siw *ServerInterfaceWrapper) GetTablesStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTablesStats(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/activity", wrapper.GetActivity)
	router.POST(options.BaseURL+"/api/ai/generate", wrapper.AiGenerate)
	router.POST(options.BaseURL+"/api/analyze", wrapper.AnalyzeQuery)
	router.POST(options.BaseURL+"/api/connect", wrapper.Connect)
	router.GET(options.BaseURL+"/api/connection", wrapper.GetConnectionInfo)
	router.GET(options.BaseURL+"/api/databases", wrapper.ListDatabases)
	router.POST(options.BaseURL+"/api/disconnect", wrapper.Disconnect)
	router.POST(options.BaseURL+"/api/explain", wrapper.ExplainQuery)
	router.POST(options.BaseURL+"/api/export", wrapper.ExportQuery)
	router.GET(options.BaseURL+"/api/functions/:function", wrapper.GetFunctionDefinition)
	router.DELETE(options.BaseURL+"/api/history", wrapper.ClearHistory)
	router.GET(options.BaseURL+"/api/history", wrapper.ListHistory)
	router.GET(options.BaseURL+"/api/info", wrapper.GetAppInfo)
	router.GET(options.BaseURL+"/api/objects", wrapper.ListObjects)
	router.POST(options.BaseURL+"/api/query", wrapper.RunQuery)
	router.POST(options.BaseURL+"/api/query/cancel", wrapper.CancelQuery)
	router.GET(options.BaseURL+"/api/saved-queries", wrapper.ListSavedQueries)
	router.POST(options.BaseURL+"/api/saved-queries", wrapper.CreateSavedQuery)
	router.DELETE(options.BaseURL+"/api/saved-queries/:id", wrapper.DeleteSavedQuery)
	router.GET(options.BaseURL+"/api/saved-queries/:id", wrapper.GetSavedQuery)
	router.PUT(options.BaseURL+"/api/saved-queries/:id", wrapper.UpdateSavedQuery)
	router.GET(options.BaseURL+"/api/schemas", wrapper.ListSchemas)
	router.GET(options.BaseURL+"/api/server_settings", wrapper.GetServerSettings)
	router.GET(options.BaseURL+"/api/settings", wrapper.GetSettings)
	router.PUT(options.BaseURL+"/api/settings", wrapper.UpdateSettings)
	router.POST(options.BaseURL+"/api/switchdb", wrapper.SwitchDatabase)
	router.GET(options.BaseURL+"/api/tables/:table", wrapper.GetTableColumns)
	router.GET(options.BaseURL+"/api/tables/:table/constraints", wrapper.GetTableConstraints)
	router.GET(options.BaseURL+"/api/tables/:table/indexes", wrapper.GetTableIndexes)
	router.GET(options.BaseURL+"/api/tables/:table/info", wrapper.GetTableInfo)
	router.GET(options.BaseURL+"/api/tables/:table/rows", wrapper.GetTableRows)
	router.GET(options.BaseURL+"/api/tables_stats", wrapper.GetTablesStats)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RbX3PbuBH/Khi2Tx0mcnp3ffCbY7upO2kSR9ebtjc3GphcybgjAQYAbSsZffcO/pEg",
	"CFC0Y/mcuSfLwgLY/WGxu9hdfckKVjeMApUiO/6SieIaaqw/nhSS3BC5VZ8bzhrgkoAewU1TkQJLwqj6",
	"V24byI4zITmhm2yXZ0VFgMoVLkseHS+xxFdYQHyw5emVG1J63xMqYQNcDXxqgW+jU4TEMr5TKyDO3y0m",
	"cgU3QOWe4ZUZG9Hs8ozDp5ZwKLPjnzXXntR253yA4xA1x7YTzINlwN6YmV9yxwy7+hUKqRg+IW+AAscS",
	"PsKnFoQcH+nkkdQgBN4YQiKh1h/+zGGdHWd/WvQKtLDaszgh/zJT1Gy7HOYcb/UZclY3cgZqhs4Dbp9s",
	"omHUiDAUDu6aCtO0VolP1X52FFE+WCrOjpN8xEXBqEypFGfVDD3SVHm3UHT/prmgazbe/Qa4iMu/iyxz",
	"imkBVVJbJL5aDW5igmFLF2P0FKrqJ1y1WmzaVhW+UhBI3kIerJpndy827IX98i89aqesamsaQ7quU0iX",
	"sMZtJVc38/be5RkRq4aTGvPt6jfwbcwVYxVgqmgoruNXp189Nq1hggRa6dm0ecZFb22Jvf28xUciRM+D",
	"UQqFTB55y2fcEUU0sThhNK6chRmHMg7TpHG6ZiJ+0g3jMg5s0vBPXhJfUL2p3aIz556BdwvFwDjnnPEJ",
	"Y6WG93NgyKLr3ym2kge5ZrzG+nugba2WKsRNlme/igG/PSgp1xow5ByVXT/G2d9bqpXgDNaEdoofxBZ8",
	"09YuGondXm/maPg3QsvoQIXpprVWeXxHU5eXg2w5TTn53AZLcU1iFZaksuHTrBtsVxsI6XGee9AMWRvs",
	"ZkGIwf8PIiTj23Mq+faeEYCLPlb1QIfUpfrb91keuWMpNVYuFIpWQrnC8XubCvE4u10VrKWJSz3LietA",
	"zHhy77b60vn7OCmGPE9AO3GrqeTkHhHU4KwiQZRkElcxIEIzYfd1M2LMX6qbm7QX6ch6bhTgLMNENGBZ",
	"EG0lY95BuXmt60MAxxwFKJmZ95z0mLq+R2c5ux0yN0s3+tApphiD/4OTcHjkQ0wtI0PV92GIHdkS30B5",
	"6ZQjODEOeOKGT5saEAUnTdLGk7iFF9eYp+KHuGlQCrlJqASRVeLN2JRpyWLGxiw1FCtigjQrnRS5j+Bg",
	"0+mTuKBNu+dxZ+Pf7DjL8r3gTxPvg3V6dgrj8Alh8VObRYXXl+INZ20TiXVswDH/bpnl3nfLh9erxhI4",
	"wRX5DOXqhsDt4y0tlAWmBTzeilK9BB5xuZEB/prVHhO88bOz0mbN7BE9tdxTDh97J2Za1ywT93p1JkPM",
	"iRDyXs+/LnhMJoGWbVGAEOkQRRiCmAmNpQiWt0QW12evH5JSCmSYTPD8qA7zlFEhOSY0GR7c18lPPySS",
	"5/WQN7m3V1LAC1rC3dPI1icD4t6SiFVLyacW7pXqiCMweMr0Cw+YmMAklisgCqmVIJ8hGXGBkKS2Wd8Z",
	"4Zs2F+kVdeCcGg4tT087WDf32Q6YTMr/kd2KZxITN8O3sweeGgnBecoI151PMsq+Zwjsr2bl9oUcH5ba",
	"gFhNHYRP2Qcm5IbD8vItchYOXaltgKOTDxddcHicNZsKpP2uy0FlRy9fvTxSErIGKG5Idpx99/Lo5Xea",
	"IXmtUVzghiywV6nZgEZB6YoO3y/K7Dh7A7Kr5ig4jAvQC/z16ChITntViYVOCnVlofn5f7fZ2FOHQWZX",
	"ZkIVEVIfl2hrY52yjy2lhG6QekESEGjNWY2azUpILFed1GqOwYEsNrYYoG+MzQwOsegLBpnRDBDyNSu3",
	"90JhuvgRVlt2QyWUvIXdVx7DXAass4/g7mhKtLx8G+DuxtSQAZ1i2XJcoS4d1YNOcbX9PAW4Ibi0WYBD",
	"QD7IYDwx2n7qIqbeRnrEHYWP8/l/Prw9uXiHTt6dvP3v/84R1oCbfEkHsE2OpwG22fUDYRsUBp4Y3aBy",
	"EAG4p0DaDO/y7PtHZGCYrZ/ef41JBWVwxnYcSYYwiriE0UHbuC1lyANEnhP2iHFUEtFVc5ApYoe2RaKi",
	"5RyoREV4dg4KB45IIvGWCHnWUT2WU9sTCI0RUGwgtu4dvAp8RSCyJsJV1VEJxCiS14AE8BsbpBi5O/TS",
	"1/2spzng4YfPxYjsliQQtmfPeA4l5ljXdR2d0LSU54bgD+o1rPTTXiPqLeDO1T2TuDIuDwnrsP54AFzD",
	"ADzPJNzJRSFuonTdUy2GMuPKTin9RFig0+VPyob9c/n+3ZP7kde4RNyBlmc/POXeWh2QKXIlHZlBy+ib",
	"VUwxAs2pYZdcW3xxH3dTXi1SGlavHI5rkMBFdvyzevmrpxKW15nLQnQ5vCzUsYnM2u6XA97riBwRvB0V",
	"Kn2y0Es64RS6DWcFlC0HJFjLC0AFKz1zem3KheYNWoF5/wRRYgWY27Lis3QcmkHtJo2KOZl2eToC6OWJ",
	"6YorPFplqUhNZOZrRleh+OEojyQO4suw9VpAYp3YModUt7DuHAHbkiBbCUa3RF4jneVAJssRiVWCA3Ba",
	"5tIcyRyDbT475NvWbhF7aTVNH0UObxJuGmTzKgjTEq1BPWcBrSu8Eb18xqNMx5zvLc1XyojLUl97XH0Y",
	"5PX210BMqWsXzUMF10zTIysVqnETQHNSVd3oRi0LJbraIrOfBkrv0eHTtQLEQ4uP7R81XLv0fOLIa+rO",
	"kViopv9dFLrVcuJ1r8cPCeyw2fOJkX24u9BcI4y4lyT00BX4BsoXNnM4eaW7+rlplJnhSbzC/eHCjHl1",
	"0b4LY8ZrVVNb6x5Jt2rbLzoaBYdpUo2ppW5Q8LY/jG6GvQ2ztPPVAbaPpj9Mk4YH2TZUUk2B8IhkrKKL",
	"L6TcTQVwZ/r7AeL7A2Tdg/I8QuOHZxS04CGIeTIM+YYhmlS3ZVLNdIzjw6Pc+MWZvr1tBKR/64aiJ8Dp",
	"mRiEZ6DEBvKkJeh/dpV2U5bmd8912vgwmenscqFOql5Mne5cCZCS0I2YekssNenSUf5+sZ1hBDmeERaD",
	"FEgAgJfgF8OJPgpzxH8cwVPvjNThT7wmHADjd4Q2P1XliTptd3zZHmYhvkasb8dYRFRHN12VV+nngm3L",
	"6gPUgxjhoPfruRcF0ZpxROF2WIjo8TbymBJdSdZr0NWpcdXCNBYuvui/k/lM27Xmek32e1dpf7X1dIHI",
	"vE4c8xO7Gd7BUMaeFco8aPGQabnxsp4ihe2i6Dr+xAyce9pvGOuw03EW6I46BvyPFvQenRTaujsN9iN9",
	"Yem+dZRNu+UMgDVhGluHWxrX6Yxp3+f4PBGdAWTcADt4RulYMyDIZ9AJRs5ukeuETMPouggnYfxoGvgO",
	"AWN+74LCq6MDVhQSywjG5cqY2OwB0ujpjJf6t6z9bPcr0ZPlaZZnZ+fL08ivRA+vaF4zbETdPuANoToX",
	"o1UliMm7QeOFlF8PVU23FO7XMbHUZM8j02xLOeZCab7G6X0j3fC+Odrd7v8BAAD//39HV1n+QwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
