// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ExportRequestFormat.
const (
	Csv  ExportRequestFormat = "csv"
	Json ExportRequestFormat = "json"
)

// Defines values for GetTableRowsParamsSortOrder.
const (
	ASC  GetTableRowsParamsSortOrder = "ASC"
	DESC GetTableRowsParamsSortOrder = "DESC"
)

// Activity defines model for Activity.
type Activity struct {
	Application   string `json:"application"`
	ClientAddr    string `json:"client_addr"`
	Database      string `json:"database"`
	Duration      string `json:"duration"`
	Pid           int    `json:"pid"`
	Query         string `json:"query"`
	State         string `json:"state"`
	User          string `json:"user"`
	WaitEvent     string `json:"wait_event"`
	WaitEventType string `json:"wait_event_type"`
}

// AiGenerateRequest defines model for AiGenerateRequest.
type AiGenerateRequest struct {
	Database string       `json:"database"`
	Messages *[]AiMessage `json:"messages,omitempty"`
	Prompt   string       `json:"prompt"`
}

// AiGenerateResponse defines model for AiGenerateResponse.
type AiGenerateResponse struct {
	Explanation string `json:"explanation"`
	Sql         string `json:"sql"`
}

// AiMessage defines model for AiMessage.
type AiMessage struct {
	Content string `json:"content"`
	Role    string `json:"role"`
}

// AiTabNameRequest defines model for AiTabNameRequest.
type AiTabNameRequest struct {
	Sql string `json:"sql"`
}

// AiTabNameResponse defines model for AiTabNameResponse.
type AiTabNameResponse struct {
	Name string `json:"name"`
}

// AppInfo defines model for AppInfo.
type AppInfo struct {
	Version *string `json:"version,omitempty"`
}

// CancelRequest defines model for CancelRequest.
type CancelRequest struct {
	TabId string `json:"tab_id"`
}

// CellValue defines model for CellValue.
type CellValue = *string

// Column defines model for Column.
type Column struct {
	Comment      *string `json:"comment,omitempty"`
	DefaultValue *string `json:"default_value"`
	IsPrimaryKey bool    `json:"is_primary_key"`
	Name         string  `json:"name"`
	Nullable     bool    `json:"nullable"`
	Position     int     `json:"position"`
	Type         string  `json:"type"`
}

// ConnectRequest defines model for ConnectRequest.
type ConnectRequest struct {
	Url string `json:"url"`
}

// ConnectionInfo defines model for ConnectionInfo.
type ConnectionInfo struct {
	Connected *bool  `json:"connected,omitempty"`
	Database  string `json:"database"`
	Host      string `json:"host"`
	Port      int    `json:"port"`
	User      string `json:"user"`
	Version   string `json:"version"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExportRequest defines model for ExportRequest.
type ExportRequest struct {
	Format ExportRequestFormat `json:"format"`
	Query  string              `json:"query"`
}

// ExportRequestFormat defines model for ExportRequest.Format.
type ExportRequestFormat string

// FunctionDefinition defines model for FunctionDefinition.
type FunctionDefinition struct {
	Arguments  string `json:"arguments"`
	Definition string `json:"definition"`
	Kind       string `json:"kind"`
	Language   string `json:"language"`
	Name       string `json:"name"`
	ReturnType string `json:"return_type"`
	Schema     string `json:"schema"`
	Volatility string `json:"volatility"`
}

// HistoryEntry defines model for HistoryEntry.
type HistoryEntry struct {
	Database   string `json:"database"`
	DurationMs int64  `json:"duration_ms"`
	Error      string `json:"error"`
	ExecutedAt string `json:"executed_at"`
	Id         int    `json:"id"`
	RowCount   int    `json:"row_count"`
	Sql        string `json:"sql"`
}

// HistoryResponse defines model for HistoryResponse.
type HistoryResponse struct {
	Entries []HistoryEntry `json:"entries"`
	Total   int            `json:"total"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	Query string `json:"query"`
	TabId string `json:"tab_id"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	ColumnTypes []string      `json:"column_types"`
	Columns     []string      `json:"columns"`
	DurationMs  int64         `json:"duration_ms"`
	Error       *string       `json:"error,omitempty"`
	RowCount    int           `json:"row_count"`
	Rows        [][]CellValue `json:"rows"`
}

// SavedQuery defines model for SavedQuery.
type SavedQuery struct {
	CreatedAt   string `json:"created_at"`
	Database    string `json:"database"`
	Description string `json:"description"`
	Id          string `json:"id"`
	Shared      bool   `json:"shared"`
	Sql         string `json:"sql"`
	Tags        string `json:"tags"`
	Title       string `json:"title"`
	UpdatedAt   string `json:"updated_at"`
}

// SavedQueryInput defines model for SavedQueryInput.
type SavedQueryInput struct {
	Database    *string `json:"database,omitempty"`
	Description *string `json:"description,omitempty"`
	Sql         string  `json:"sql"`
	Tags        *string `json:"tags,omitempty"`
	Title       string  `json:"title"`
}

// SchemaGroup defines model for SchemaGroup.
type SchemaGroup struct {
	Functions         []SchemaObject `json:"functions"`
	MaterializedViews []SchemaObject `json:"materialized_views"`
	Sequences         []SchemaObject `json:"sequences"`
	Tables            []SchemaObject `json:"tables"`
	Types             []SchemaObject `json:"types"`
	Views             []SchemaObject `json:"views"`
}

// SchemaObject defines model for SchemaObject.
type SchemaObject struct {
	Comment *string `json:"comment,omitempty"`
	Name    string  `json:"name"`
	Schema  string  `json:"schema"`
	Type    string  `json:"type"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Success *bool `json:"success,omitempty"`
}

// SwitchDBRequest defines model for SwitchDBRequest.
type SwitchDBRequest struct {
	Database string `json:"database"`
}

// TableConstraint defines model for TableConstraint.
type TableConstraint struct {
	Columns    *[]string `json:"columns,omitempty"`
	Definition string    `json:"definition"`
	Name       string    `json:"name"`
	Type       string    `json:"type"`
}

// TableIndex defines model for TableIndex.
type TableIndex struct {
	Columns    *[]string `json:"columns,omitempty"`
	Definition string    `json:"definition"`
	IsPrimary  bool      `json:"is_primary"`
	IsUnique   bool      `json:"is_unique"`
	Name       string    `json:"name"`
}

// TableInfo defines model for TableInfo.
type TableInfo struct {
	IndexSize   string `json:"index_size"`
	RowEstimate int64  `json:"row_estimate"`
	TableSize   string `json:"table_size"`
	TotalSize   string `json:"total_size"`
}

// TableRowsResult defines model for TableRowsResult.
type TableRowsResult struct {
	ColumnTypes []string      `json:"column_types"`
	Columns     []string      `json:"columns"`
	Page        int           `json:"page"`
	PageSize    int           `json:"page_size"`
	Rows        [][]CellValue `json:"rows"`
	TotalCount  int           `json:"total_count"`
}

// ListHistoryParams defines parameters for ListHistory.
type ListHistoryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListSavedQueriesParams defines parameters for ListSavedQueries.
type ListSavedQueriesParams struct {
	Database *string `form:"database,omitempty" json:"database,omitempty"`
}

// UpdateSettingsJSONBody defines parameters for UpdateSettings.
type UpdateSettingsJSONBody map[string]string

// GetTableRowsParams defines parameters for GetTableRows.
type GetTableRowsParams struct {
	Limit      *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                         `form:"offset,omitempty" json:"offset,omitempty"`
	SortColumn *string                      `form:"sort_column,omitempty" json:"sort_column,omitempty"`
	SortOrder  *GetTableRowsParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`
}

// GetTableRowsParamsSortOrder defines parameters for GetTableRows.
type GetTableRowsParamsSortOrder string

// AiGenerateJSONRequestBody defines body for AiGenerate for application/json ContentType.
type AiGenerateJSONRequestBody = AiGenerateRequest

// AiTabNameJSONRequestBody defines body for AiTabName for application/json ContentType.
type AiTabNameJSONRequestBody = AiTabNameRequest

// AnalyzeQueryJSONRequestBody defines body for AnalyzeQuery for application/json ContentType.
type AnalyzeQueryJSONRequestBody = QueryRequest

// ConnectJSONRequestBody defines body for Connect for application/json ContentType.
type ConnectJSONRequestBody = ConnectRequest

// ExplainQueryJSONRequestBody defines body for ExplainQuery for application/json ContentType.
type ExplainQueryJSONRequestBody = QueryRequest

// ExportQueryJSONRequestBody defines body for ExportQuery for application/json ContentType.
type ExportQueryJSONRequestBody = ExportRequest

// RunQueryJSONRequestBody defines body for RunQuery for application/json ContentType.
type RunQueryJSONRequestBody = QueryRequest

// CancelQueryJSONRequestBody defines body for CancelQuery for application/json ContentType.
type CancelQueryJSONRequestBody = CancelRequest

// CreateSavedQueryJSONRequestBody defines body for CreateSavedQuery for application/json ContentType.
type CreateSavedQueryJSONRequestBody = SavedQueryInput

// UpdateSavedQueryJSONRequestBody defines body for UpdateSavedQuery for application/json ContentType.
type UpdateSavedQueryJSONRequestBody = SavedQueryInput

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody UpdateSettingsJSONBody

// SwitchDatabaseJSONRequestBody defines body for SwitchDatabase for application/json ContentType.
type SwitchDatabaseJSONRequestBody = SwitchDBRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Running queries from pg_stat_activity
	// (GET /api/activity)
	GetActivity(c *gin.Context)
	// Generate SQL from natural language
	// (POST /api/ai/generate)
	AiGenerate(c *gin.Context)
	// Generate a short tab name from SQL
	// (POST /api/ai/tab-name)
	AiTabName(c *gin.Context)
	// EXPLAIN ANALYZE a SQL query
	// (POST /api/analyze)
	AnalyzeQuery(c *gin.Context)
	// Connect to a PostgreSQL database
	// (POST /api/connect)
	Connect(c *gin.Context)
	// Get current connection info
	// (GET /api/connection)
	GetConnectionInfo(c *gin.Context)
	// List all databases on the server
	// (GET /api/databases)
	ListDatabases(c *gin.Context)
	// Disconnect from the database
	// (POST /api/disconnect)
	Disconnect(c *gin.Context)
	// EXPLAIN a SQL query
	// (POST /api/explain)
	ExplainQuery(c *gin.Context)
	// Export query results as CSV or JSON
	// (POST /api/export)
	ExportQuery(c *gin.Context)
	// Get function or procedure source code
	// (GET /api/functions/{function})
	GetFunctionDefinition(c *gin.Context, function string)
	// Clear all query history
	// (DELETE /api/history)
	ClearHistory(c *gin.Context)
	// List query history
	// (GET /api/history)
	ListHistory(c *gin.Context, params ListHistoryParams)
	// Get app version and feature flags
	// (GET /api/info)
	GetAppInfo(c *gin.Context)
	// All objects grouped by schema and type
	// (GET /api/objects)
	ListObjects(c *gin.Context)
	// Execute SQL query
	// (POST /api/query)
	RunQuery(c *gin.Context)
	// Cancel a running query
	// (POST /api/query/cancel)
	CancelQuery(c *gin.Context)
	// List saved queries
	// (GET /api/saved-queries)
	ListSavedQueries(c *gin.Context, params ListSavedQueriesParams)
	// Create a saved query
	// (POST /api/saved-queries)
	CreateSavedQuery(c *gin.Context)
	// Delete a saved query
	// (DELETE /api/saved-queries/{id})
	DeleteSavedQuery(c *gin.Context, id string)
	// Get a saved query by ID
	// (GET /api/saved-queries/{id})
	GetSavedQuery(c *gin.Context, id string)
	// Update a saved query
	// (PUT /api/saved-queries/{id})
	UpdateSavedQuery(c *gin.Context, id string)
	// List database schemas
	// (GET /api/schemas)
	ListSchemas(c *gin.Context)
	// PostgreSQL server settings
	// (GET /api/server_settings)
	GetServerSettings(c *gin.Context)
	// Get all settings
	// (GET /api/settings)
	GetSettings(c *gin.Context)
	// Update settings
	// (PUT /api/settings)
	UpdateSettings(c *gin.Context)
	// Switch to a different database
	// (POST /api/switchdb)
	SwitchDatabase(c *gin.Context)
	// Get table column definitions
	// (GET /api/tables/{table})
	GetTableColumns(c *gin.Context, table string)
	// Table constraints
	// (GET /api/tables/{table}/constraints)
	GetTableConstraints(c *gin.Context, table string)
	// Table indexes
	// (GET /api/tables/{table}/indexes)
	GetTableIndexes(c *gin.Context, table string)
	// Table size and row estimates
	// (GET /api/tables/{table}/info)
	GetTableInfo(c *gin.Context, table string)
	// Paginated table data
	// (GET /api/tables/{table}/rows)
	GetTableRows(c *gin.Context, table string, params GetTableRowsParams)
	// All tables size and row stats
	// (GET /api/tables_stats)
	GetTablesStats(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetActivity operation middleware
func (siw *ServerInterfaceWrapper) GetActivity(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActivity(c)
}

// AiGenerate operation middleware
func (siw *ServerInterfaceWrapper) AiGenerate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AiGenerate(c)
}

// AiTabName operation middleware
func (siw *ServerInterfaceWrapper) AiTabName(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AiTabName(c)
}

// AnalyzeQuery operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AnalyzeQuery(c)
}

// Connect operation middleware
func (siw *ServerInterfaceWrapper) Connect(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Connect(c)
}

// GetConnectionInfo operation middleware
func (siw *ServerInterfaceWrapper) GetConnectionInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConnectionInfo(c)
}

// ListDatabases operation middleware
func (siw *ServerInterfaceWrapper) ListDatabases(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDatabases(c)
}

// Disconnect operation middleware
func (siw *ServerInterfaceWrapper) Disconnect(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Disconnect(c)
}

// ExplainQuery operation middleware
func (siw *ServerInterfaceWrapper) ExplainQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExplainQuery(c)
}

// ExportQuery operation middleware
func (siw *ServerInterfaceWrapper) ExportQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportQuery(c)
}

// GetFunctionDefinition operation middleware
func (siw *ServerInterfaceWrapper) GetFunctionDefinition(c *gin.Context) {

	var err error

	// ------------- Path parameter "function" -------------
	var function string

	err = runtime.BindStyledParameterWithOptions("simple", "function", c.Param("function"), &function, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter function: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFunctionDefinition(c, function)
}

// ClearHistory operation middleware
func (siw *ServerInterfaceWrapper) ClearHistory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ClearHistory(c)
}

// ListHistory operation middleware
func (siw *ServerInterfaceWrapper) ListHistory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListHistory(c, params)
}

// GetAppInfo operation middleware
func (siw *ServerInterfaceWrapper) GetAppInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAppInfo(c)
}

// ListObjects operation middleware
func (siw *ServerInterfaceWrapper) ListObjects(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListObjects(c)
}

// RunQuery operation middleware
func (siw *ServerInterfaceWrapper) RunQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RunQuery(c)
}

// CancelQuery operation middleware
func (siw *ServerInterfaceWrapper) CancelQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelQuery(c)
}

// ListSavedQueries operation middleware
func (siw *ServerInterfaceWrapper) ListSavedQueries(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSavedQueriesParams

	// ------------- Optional query parameter "database" -------------

	err = runtime.BindQueryParameter("form", true, false, "database", c.Request.URL.Query(), &params.Database)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter database: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSavedQueries(c, params)
}

// CreateSavedQuery operation middleware
func (siw *ServerInterfaceWrapper) CreateSavedQuery(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSavedQuery(c)
}

// DeleteSavedQuery operation middleware
func (siw *ServerInterfaceWrapper) DeleteSavedQuery(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSavedQuery(c, id)
}

// GetSavedQuery operation middleware
func (siw *ServerInterfaceWrapper) GetSavedQuery(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSavedQuery(c, id)
}

// UpdateSavedQuery operation middleware
func (siw *ServerInterfaceWrapper) UpdateSavedQuery(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateSavedQuery(c, id)
}

// ListSchemas operation middleware
func (siw *ServerInterfaceWrapper) ListSchemas(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSchemas(c)
}

// GetServerSettings operation middleware
func (siw *ServerInterfaceWrapper) GetServerSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServerSettings(c)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSettings(c)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateSettings(c)
}

// SwitchDatabase operation middleware
func (siw *ServerInterfaceWrapper) SwitchDatabase(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SwitchDatabase(c)
}

// GetTableColumns operation middleware
func (siw *ServerInterfaceWrapper) GetTableColumns(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableColumns(c, table)
}

// GetTableConstraints operation middleware
func (siw *ServerInterfaceWrapper) GetTableConstraints(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableConstraints(c, table)
}

// GetTableIndexes operation middleware
func (siw *ServerInterfaceWrapper) GetTableIndexes(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableIndexes(c, table)
}

// GetTableInfo operation middleware
func (siw *ServerInterfaceWrapper) GetTableInfo(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableInfo(c, table)
}

// GetTableRows operation middleware
func (siw *ServerInterfaceWrapper) GetTableRows(c *gin.Context) {

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", c.Param("table"), &table, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter table: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTableRowsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort_column" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_column", c.Request.URL.Query(), &params.SortColumn)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_column: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort_order" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_order", c.Request.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_order: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTableRows(c, table, params)
}

// GetTablesStats operation middleware
func (siw *ServerInterfaceWrapper) GetTablesStats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTablesStats(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/activity", wrapper.GetActivity)
	router.POST(options.BaseURL+"/api/ai/generate", wrapper.AiGenerate)
	router.POST(options.BaseURL+"/api/ai/tab-name", wrapper.AiTabName)
	router.POST(options.BaseURL+"/api/analyze", wrapper.AnalyzeQuery)
	router.POST(options.BaseURL+"/api/connect", wrapper.Connect)
	router.GET(options.BaseURL+"/api/connection", wrapper.GetConnectionInfo)
	router.GET(options.BaseURL+"/api/databases", wrapper.ListDatabases)
	router.POST(options.BaseURL+"/api/disconnect", wrapper.Disconnect)
	router.POST(options.BaseURL+"/api/explain", wrapper.ExplainQuery)
	router.POST(options.BaseURL+"/api/export", wrapper.ExportQuery)
	router.GET(options.BaseURL+"/api/functions/:function", wrapper.GetFunctionDefinition)
	router.DELETE(options.BaseURL+"/api/history", wrapper.ClearHistory)
	router.GET(options.BaseURL+"/api/history", wrapper.ListHistory)
	router.GET(options.BaseURL+"/api/info", wrapper.GetAppInfo)
	router.GET(options.BaseURL+"/api/objects", wrapper.ListObjects)
	router.POST(options.BaseURL+"/api/query", wrapper.RunQuery)
	router.POST(options.BaseURL+"/api/query/cancel", wrapper.CancelQuery)
	router.GET(options.BaseURL+"/api/saved-queries", wrapper.ListSavedQueries)
	router.POST(options.BaseURL+"/api/saved-queries", wrapper.CreateSavedQuery)
	router.DELETE(options.BaseURL+"/api/saved-queries/:id", wrapper.DeleteSavedQuery)
	router.GET(options.BaseURL+"/api/saved-queries/:id", wrapper.GetSavedQuery)
	router.PUT(options.BaseURL+"/api/saved-queries/:id", wrapper.UpdateSavedQuery)
	router.GET(options.BaseURL+"/api/schemas", wrapper.ListSchemas)
	router.GET(options.BaseURL+"/api/server_settings", wrapper.GetServerSettings)
	router.GET(options.BaseURL+"/api/settings", wrapper.GetSettings)
	router.PUT(options.BaseURL+"/api/settings", wrapper.UpdateSettings)
	router.POST(options.BaseURL+"/api/switchdb", wrapper.SwitchDatabase)
	router.GET(options.BaseURL+"/api/tables/:table", wrapper.GetTableColumns)
	router.GET(options.BaseURL+"/api/tables/:table/constraints", wrapper.GetTableConstraints)
	router.GET(options.BaseURL+"/api/tables/:table/indexes", wrapper.GetTableIndexes)
	router.GET(options.BaseURL+"/api/tables/:table/info", wrapper.GetTableInfo)
	router.GET(options.BaseURL+"/api/tables/:table/rows", wrapper.GetTableRows)
	router.GET(options.BaseURL+"/api/tables_stats", wrapper.GetTablesStats)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RbX3PcthH/Khi2Tx3apzRJH/SmSGqqjmtbPjfTNpO5gci9ExISoAFQ0llz372DfyQI",
	"AjxK1iny5MmysFzs/rDYXeyu7rOC1Q2jQKXIju8zUVxDjfWPJ4UkN0Ru1c8NZw1wSUCv4KapSIElYVT9",
	"V24byI4zITmhm2yXZ0VFgMoVLkseXS+xxFdYQHyx5WnODSm93xMqYQNcLXxqgW+jnwiJZXynVkBcvltM",
	"5ApugMo9yyuzNqLZ5RmHTy3hUGbHP2upPa3tzvkAxyFqTmynmAfLQLyxML/kThh29SsUUgl8Qn4EChxL",
	"+ACfWhByfKSTR1KDEHhjCImEWv/wZw7r7Dj706I3oIW1nsUJ+Zf5RH1t2WHO8VafIWd1I2egZug84Pbp",
	"JhpGjQpD5eCuqTBNW5X4VO0XRxHlA1ZxcZzmIykKRmXKpDirZtiRpso7RvH9P+Krt7hOn/RsZfewT4FN",
	"cT1DFU0V3aFpLuiajfneABfxA9xF2JxiWkCVBEHiq9XAlSTEtHQxQU+hqn7CVauVpW1V4St1hpK3kAdc",
	"8+zu1Ya9sr/8S3/sp6xqaxozlbpOmUoJa9xWcnUzb+9dnhGxajipMd+ufgPfSV4xVgGmiiZxarnHPfZZ",
	"wwQJrpXnlOd5R721Jfb285iPVIieB6MUCpk88pbPsHtFNMGcMBo3zsKsQxmHadK7XjMRP+mGcRkHNhm5",
	"Ji+Jr6je1G7RxSMvQjlGMTDOOWd8wtuq5f0SGLIo/zslVvIg14zXWP8eaFsrVoW4yfLsVzGQtwcllRsE",
	"ArlIa/nHJPt7S7URnMGa0M7wg+SIb9rapVOx2+t9OVr+jdAyulBhumltWBnf0dTl5SBbTlNZSm6zvbgl",
	"sQpLUtn8b9YNttwGSnqS5x40Q9EGu1kQYvD/gwjJ+PacSr59YArj0qdVPbAhdan+9l2WR+5YyoxVDgBF",
	"K6Fc4fi9TeWonN2uCtbSxKWeFZh1JmlSEe+2+tr5+zgthjJPQDtxq6nk5AEp4OCsIlmgZBJXMSBCN2H3",
	"dV/EhL9UNzfpL9JPg7lZgPMME9mAFUG0lYxFBxXmta0PARxLFKBkvnzgR09p63tslrPboXCzbKNPnWKG",
	"Mfh/cBIOj3yIqRVkaPo+DLEjW+IbKC+dcQQnxgFP3PBpVwOi4KRJ+ngS9/DiGvNU/hB3DcogNwmTILJK",
	"PHqbMq1ZzNkYVkO1Ii5Ii9JpkfsIDjadPokL2rR7Xqc2/82OsyzfC/408T5Yp79OYRw+ISx+qSfVUl+K",
	"Hzlrm0iuYxOO+XfLsHvXsQ+vV40lcIIr8hnK1Q2B26djLZQHpgU8HUepXgJPyG7kgL+E21OCN352Vtqt",
	"mT2ip5Z7xuFj79RM25oV4kGvzmSKOZFCPuj51yWPySrWsi0KECKdoghDEHOhsRLB8pbI4vrsh8fUxAId",
	"JitUH9VhnjIqJMeEJtODhwb56YdE8rwe8yb39koqeEFLuHse3fpiQDxaErFqKfnUwoNKHXEEBk+ZnvFA",
	"iAlMYrUCopBaCfIZkhkXCElqW7aekb5pd5HmqBPn1HLoeXraAd/cFzsQMqn/B3YrXkhO3Azfzh54aiUE",
	"5zkzXHc+ySz7gSmwz83q7Ss5Piy1AbGWOkifsvdMyA2H5eUb5DwculLbAEcn7y+65PA4azYVSPu7rgaV",
	"Hb3+5vWR0pA1QHFDsuPs29dHr7/VAslrjeICN2SBvVbTBjQKylZ0+n5RZsfZjyC7dpSCw4QAzeCvR0dB",
	"dd1rqyx0Uajra81vYLjNxpE6TDK7PhmqiJD6uERbG++UfWgpJXSD1AuSgEBrzmrUbFZCYrnqtFbfGBzI",
	"YmO7GfrG2MrgEIu+45EZywAhf2Dl9kEoTHdvwnbRbmiEkrew+8JjmCuADfYR3B1NiZaXbwLc3ZpaMqBT",
	"LFuOK9SVo3zQJb565cJCCnTb+DgY5kHf5tkhDxs7k4hLfIU0YAnYMRLXjMuOzpyBOycDO8XV9vMU5Ibg",
	"0hZfDoH6oHD0zIj7FaOYVzHaI+4ofJzP//P+zcnFW3Ty9uTNf/93jrC2c1Om6gC2PYk0wLapcSBsg37M",
	"M6MbNGwiAPcUSEe/XZ5994QCDJsk0/uvMamgDM7YriPJEEaRSDw6aJsup+JngMhLwh4xjkoiuiYaMsMP",
	"oW+RqGg5BypREZ6dg8KBI5JIvCFCnnVUT5VL7Mk/xwgoMRBb93mV8pIiUFkT4arqqARiFMlrQAL4jc0N",
	"jd4deunrftbTHPDww1d6RHdLEijbi2eChVJzbOt6/oLQtJbnhuAPGjWs9tNRIxot4M61m5O4Mi4PCeuw",
	"7XsAXMN3T55JuJOLQtxE6boXcgxlxpWfUvaJsECny5+UD/vn8t3bZ48jP+AScQdann3/nHtrc0Cmt5gM",
	"ZAYtY2/WMMUINGeGXU1zce9+3E1FtUhHXj0uOa5BAhfZ8c/3mXIX+sGZueJPVzrNQhubKGjufjngvY7o",
	"EcHbUaHSJwujpFNOodtwVkDZckCCtbwAVLDSc6fXpktrnv4VmGdnkCVWgLnt5r7IwKEF1GHSmJjTaZen",
	"M4Ben5ituH6vNZaK1ERmvmV0jaHvj/JIvSbOhq3XAhJ8YmwOaW5huz8CtiVBtgGPbom8Rrq4hExxKZKr",
	"BAfgrMxVl5KlHTvzd8j3rd0i9tJqmj6LHN4k3DTIlrMQpiVaA5bqLq0rvBG9fiaiTOec7yzNF+qIy1Jf",
	"e1y9H5RT97eeTIdxFy3/BddM0yOrFapxE0BzUlXd6kaxhRJdbZHZTwOl9+jw6SYw4qnFh/aPmq5dejFx",
	"FDX1wE4sVdP/XRR6wnXida/XDwnscMb2mZF9fLjQUiOMuFeb9dAV+AbKV7ZgO3mlu7EFM580I5J48xKH",
	"SzPmtaP74ZcZr1VNbb17pMqtfb/oaBQcZjY4ZpZ6LsTb/jC2GY6UzLLObw6wfbT8YWZjPMi2oZFqCoRH",
	"JGMTXdyTcjeVwJ3p3w8Q358g69Gfl5EaP76ioBUPQcyTachXDNGkuS2TZqZzHB8eFcYvzvTtbSMg/VvP",
	"cT0DTi/EIbwAIzaQJz1B/+d66TBlaX73WqfND5OVzq4W6rTq1dTlzpUAKQndiKm3xFKTLh3l75fbGUGQ",
	"kxlhMSiBBAB4BX4x/NBHYY76T6N46p2ROvyJ14QDYPyO0O6nqjxVp/2Or9vjPMSXqPX1OIuI6ehZt/Iq",
	"/Vyw03B9gnoQJxyM3L30piBaM44o3A4bET3eRh/ToivJeg26OzXuWph5zsW9/neynmmHBd2Iz/7oKu0f",
	"yz1fIjJvAMr8ZeOM6GAoY88K5R60eshMOnlVT5HCdlF0g5ZiBs497VeMdThgOgt0Rx0D/qMFvUcnhbYe",
	"CoT9SF9Yuq8dZTPlOgNgTZjG1uGWxnW6YtqPl75MRGcAGXfADp5ROdYsCPIZdIGRs1vkBlDTMLrhzUkY",
	"P5i5yUPAmD+4ofDN0QE7Cgk2gnG5Mi42e4Q2+nPGS/0nxP3X7o9zT5anWZ6dnS9PI3+ce3hD82aQI+b2",
	"Hm8I1bUYbSpBTt4tmiik4npoanqSc7+NiaUmexmVZtvKMRdKyzUu7xvthvfN0e52/w8AAP//gjW17DZG",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
