package api

import (
	"sync"

	"github.com/macleodmac/pglet/pkg/client"
	"github.com/macleodmac/pglet/pkg/repository"
)

// Server implements ServerInterface generated by oapi-codegen.
type Server struct {
	mu     sync.RWMutex
	client *client.Client
	Repo   *repository.Repository
}

// SetClient replaces the current client (used during setup/connect).
func (s *Server) SetClient(cl *client.Client) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.client = cl
}

// getClient returns the current client (read lock).
func (s *Server) getClient() *client.Client {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.client
}

// swapClient atomically replaces the client, closing the old one.
// Returns the new client's info or an error.
func (s *Server) swapClient(cl *client.Client) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.client != nil {
		s.client.Close()
	}
	s.client = cl
}

// Compile-time check that Server implements the interface.
var _ ServerInterface = (*Server)(nil)
