package api

import (
	"github.com/macleodmac/pglet/pkg/service"
)

// Server implements ServerInterface generated by oapi-codegen.
// It delegates all business logic to a single Service struct.
type Server struct {
	svc *service.Service
}

func NewServer(svc *service.Service) *Server {
	return &Server{svc: svc}
}

// Compile-time check that Server implements the interface.
var _ ServerInterface = (*Server)(nil)
